logging:
  level:
    org:
      springframework:
        data.r2dbc: DEBUG
        transaction: TRACE

spring:
  r2dbc:
    url: r2dbc:h2:mem:///app?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password: